{"trial_id": "33", "hyperparameters": {"space": [{"class_name": "Float", "config": {"name": "lr", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 2, "max_value": 2, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 2, "max_value": 220, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 2, "max_value": 220, "step": 2, "sampling": "linear"}}], "values": {"lr": 0.0011838262168342043, "num_layers": 2, "units_0": 220, "units_1": 198}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Jonas\\AppData\\Local\\Temp\\ipykernel_30516\\881691314.py\", line 15, in fit\n    model_history = fit_and_evaluate_model(local_model, x[train_index], y[train_index], x[test_index], y[test_index], **kwargs)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Jonas\\AppData\\Local\\Temp\\ipykernel_30516\\2735516902.py\", line 3, in fit_and_evaluate_model\n    model_history = model.fit(x_train, y_train, batch_size=64, epochs=500, validation_data=(x_test, y_test), verbose=0, **kwargs)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner_utils.py\", line 71, in on_epoch_end\n    self._save_model()\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner_utils.py\", line 86, in _save_model\n    self.model.save_weights(write_filepath)\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\h5py\\_hl\\files.py\", line 562, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\GitClones\\TINF21C_Maschinelles-Lernen\\Programmierabgabe 2\\venv\\Lib\\site-packages\\h5py\\_hl\\files.py\", line 241, in make_fid\n    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"h5py\\\\_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n  File \"h5py\\\\_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n  File \"h5py\\\\h5f.pyx\", line 122, in h5py.h5f.create\nOSError: [Errno 22] Unable to synchronously create file (unable to open file: name = 'wine_score_training\\white\\trial_33\\checkpoint.weights.h5', errno = 22, error message = 'Invalid argument', flags = 13, o_flags = 302)\n"}